baseURL = "https://example.org/"

Title = "ox-hugo - Org to Hugo exporter"
theme = ["hugo-debugprint", "hugo-onyx-theme"]

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

# Remove files from destination not found in static directories
cleandestinationdir = true

# Mon Mar 05 17:17:44 EST 2018 - kmodi
# Do not enable GitInfo. As I am not committing the Markdown files to
# git repo, enabling GitInfo would cause the Lastmod dates for those
# files to be the date when I deleted them from this repo.. sigh.
# enableGitInfo = true

# https://gohugo.io/extras/highlighting/

# Syntax highlighting using Pygments
# $ python
# >>> from pygments.styles import STYLE_MAP
# >>> STYLE_MAP.keys()
# ['manni', 'igor', 'lovelace', 'xcode', 'vim', 'autumn', 'vs', 'rrt', 'native',
# 'perldoc', 'borland', 'tango', 'emacs', 'friendly', 'monokai', 'paraiso-dark',
# 'colorful', 'murphy', 'bw', 'pastie', 'algol_nu', 'paraiso-light', 'trac',
# 'default', 'algol', 'fruity']
# pygmentsStyle = "native"
# pygmentsStyle = "trac"        # This is not needed as the theme is set using external CSS -- Tue Sep 26 13:26:59 EDT 2017 - kmodi
pygmentsCodeFences = true       # This applies to Chroma too.
# Use pygmentize generated CSS file instead of inlining the code codes in the HTML.
# See https://gohugo.io/tools/syntax-highlighting/#pygments and
# https://github.com/richleland/pygments-css
pygmentsUseClasses = true       # This applies to Chroma too.
pygmentsUseClassic = false      # Needs Hugo 0.28+, default=false => Use Chroma for syntax highlighting

enableEmoji = true

LanguageCode = "en-us" # Used in RSS generation

disableFastRender = true        # Hugo 0.30

[Permalinks]
  # post = "/:year/:month/:title/"
  # Below, we have
  #   foo = "bar"
  # where foo = section name without double quotes for which we want to have
  # the custom permalinks. If foo is 'posts', it will apply to content in
  # content/posts/ dir. The "bar" portion is how you want the links to look.
  # https://gohugo.io/content-management/urls/#permalink-configuration-values
  doc = "/doc/:filename/"
  test = "/test/:slug/"

[Params]
  name = "ox-hugo"
  description = "Org mode to Hugo exporter<br />Write your Hugo posts in native Org mode."

  # Go date formats: https://golang.org/pkg/time/#pkg-constants
  dateform = "Mon Jan 2, 2006"

  github_user = "kaushalmodi"
  github_repo = "ox-hugo"
  github_banner = true

  images = ["/favicon-196x196.png"] # Used in twitter_cards.html partial

  custom_css = [ # Pygments Trac theme
                 # "css/trac_pygments.css" # Needs pygmentsUseClasses to be true
                 # Chroma Trac theme
                 # "css/trac_chroma.css" # Needs pygmentsUseClasses to be true
                 # Chroma GitHub theme
                 "css/github_chroma.css" # Needs pygmentsUseClasses to be true
                 , "css/style.css"
               ]
  custom_css_absolute = [ # Iosevka fonts
                          "https://cdn.rawgit.com/kaushalmodi/iosevka-mirror/v1.14.1/iosevka.css"
                        ]
  custom_js  = []

  # favicon = "favicon.ico"

  [Params.source]
    url = "https://github.com/kaushalmodi/ox-hugo"
    org_dir = "doc"
    org_file = "doc/ox-hugo-manual.org"

  [Params.sidebar]
    logo = "favicon.ico"

    github_button  = true
    travis_button  = true
    codecov_button = false
    gratipay = ""

    # Mon Sep 04 23:55:36 EDT 2017 - kmodi
    # Disable this option for now.. but seems to be useful in future
    show_relations = false

  [Params.footer]
    copyright = ""
    show_powered_by = true
